---
title: ""
---

# Audiencia

El curso de **Análisis Espacial del Dengue en R** esta complementado con el desarrollo de paquetes colectivamente llamados **dengueverse** (rgeomex, denhotspots, deneggs, dencontrol, denepikit) y el [manual para la identificación de los hotspots en las localidades urbanas endémicas](https://fdzul.github.io/manual_hotspots/). Tanto los cursos, los paquetes y el manual, no solo está dirigido al personal operativo, mandos medios y directivos de los Programas de Prevención y Control de las arbovirosis transmitidas por *Aedes* de la Secretaría de Salud de México, sino también a la comunidad académica relacionada con la investigación operativa sobre el análisis espacial de dengue y al público en general interesado en el tema.

# Objetivo General

El curso títulado **Análisis Espacial del Dengue en R** tiene como objetivo central desarrollar las competencias específicas para la identificación del riesgo de transmisión del dengue en áreas urbanas y metropolitanas de México usando información entomológica y epidemiológica con la finalidad orientar las acciones de prevención y control del Manejo Integrado de las Arbovirosis en México.

# Objetivos Específicos

1.  Identificar los hotspots de la transmisión de las arbovirosis en las localidades urbanas endémicas de México.

2.  Identificar los hotspots de la abundancia de huevos del vector del dengue en las localidades urbanas endémicas de México.

3.  Generar los mapas de calor en las localidades urbanas endémicas de México.

4.  Desarrollar un modelo estratégico de focalización del dengue en las localidades urbanas endémicas de México.

# Requisitos

- Computadora
- Experiencia en la instalación de Software
- Claves del SINAVE y del Sistema Integral de Monitoreo de Vectores
- Bases de datos de ovitrampas de años anteriores (en txt o zip)
- Bajar la carpeta geocodificación.

